version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - common_network
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  common_network:
    external: true
